# Generated by Django 4.1.7 on 2023-02-26 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.IntegerField(default=0, primary_key=True, serialize=False),
                ),
                ("date", models.CharField(max_length=10)),
                ("score", models.IntegerField(default=0)),
                ("content", models.CharField(max_length=500)),
                ("deletestatus", models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.IntegerField(default=0, primary_key=True, serialize=False),
                ),
                ("Username", models.CharField(max_length=10)),
                ("password", models.CharField(max_length=8)),
                ("level", models.IntegerField(default=0)),
            ],
        ),
    ]
