# Generated by Django 4.1.7 on 2023-03-13 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GroupProjectCode", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(default="In process", max_length=50),
        ),
        migrations.AlterField(
            model_name="order", name="time", field=models.DateTimeField(),
        ),
    ]
