# Generated by Django 4.1.5 on 2023-02-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Commodities",
            fields=[
                (
                    "commodities_id",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="商品唯一id"
                    ),
                ),
                ("commodities_name", models.CharField(max_length=200)),
                ("commodities_description", models.CharField(max_length=200)),
                ("commodities_price", models.IntegerField(default=0)),
                ("commodities_url", models.CharField(max_length=200)),
                ("commodities_num_bookings", models.IntegerField(default=0)),
                ("commodities_logic_delete", models.BooleanField(default=0)),
            ],
        ),
    ]
