# Generated by Django 4.1.7 on 2023-03-07 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Trip",
            fields=[
                ("Trip_id", models.IntegerField(primary_key=True, serialize=False)),
                ("tripname", models.CharField(max_length=10)),
                ("introduction", models.CharField(max_length=500)),
                ("delete_status", models.CharField(max_length=500)),
                ("image_url", models.ImageField(upload_to="imgurl")),
                ("booked_num", models.IntegerField(null=True)),
                ("Trip_price", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("User_id", models.IntegerField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=10)),
                ("password", models.CharField(max_length=8)),
                ("level", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                ("Review_id", models.IntegerField(primary_key=True, serialize=False)),
                ("date", models.CharField(max_length=10)),
                ("rating", models.IntegerField()),
                ("content", models.CharField(max_length=500)),
                ("delete_status", models.CharField(max_length=2)),
                (
                    "Trip_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="manage.trip",
                    ),
                ),
                (
                    "User_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="manage.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("Order_id", models.IntegerField(primary_key=True, serialize=False)),
                ("amount", models.IntegerField()),
                ("time", models.CharField(max_length=500)),
                ("status", models.CharField(max_length=500)),
                ("Order_price", models.IntegerField()),
                (
                    "Trip_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="manage.trip",
                    ),
                ),
                (
                    "User_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="manage.user",
                    ),
                ),
            ],
        ),
    ]
