# Generated by Django 2.1.5 on 2023-03-08 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0005_auto_20230308_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='level',
        ),
    ]
