# Generated by Django 4.1.5 on 2023-03-19 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='商品唯一id')),
                ('trip_name', models.CharField(max_length=200)),
                ('trip_description', models.CharField(max_length=200)),
                ('trip_price', models.IntegerField(default=0)),
                ('trip_url', models.CharField(max_length=200)),
                ('trip_num_bookings', models.IntegerField(default=0)),
                ('trip_logic_delete', models.BooleanField(default=0)),
            ],
        ),
    ]
